// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'x',
    appId: '1:1',
    messagingSenderId: '1096423812863',
    projectId: 'coffee-2eb12',
    authDomain: 'coffee-2eb12.firebaseapp.com',
    storageBucket: 'coffee-2eb12.firebasestorage.app',
    measurementId: 'G-DVKW499K8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH_yG7BZGea0mYZG0HhBTLo-G-bafOM4o',
    appId: '1:1096423812863:android:98add3a267b08afca326ca',
    messagingSenderId: '1096423812863',
    projectId: 'coffee-2eb12',
    storageBucket: 'coffee-2eb12.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe2tYEKulM6RLKabzBCDBN_KISp5YZN5w',
    appId: '1:1096423812863:ios:d06c5c350a5a0065a326ca',
    messagingSenderId: '1096423812863',
    projectId: 'coffee-2eb12',
    storageBucket: 'coffee-2eb12.firebasestorage.app',
    iosBundleId: 'com.example.coffeeCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe2tYEKulM6RLKabzBCDBN_KISp5YZN5w',
    appId: '1:1096423812863:ios:d06c5c350a5a0065a326ca',
    messagingSenderId: '1096423812863',
    projectId: 'coffee-2eb12',
    storageBucket: 'coffee-2eb12.firebasestorage.app',
    iosBundleId: 'com.example.coffeeCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0fRwLd4mLbwfP28uVvPt0QCVIWM2oAQs',
    appId: '1:1096423812863:web:586c5f2e20bdc6b4a326ca',
    messagingSenderId: '1096423812863',
    projectId: 'coffee-2eb12',
    authDomain: 'coffee-2eb12.firebaseapp.com',
    storageBucket: 'coffee-2eb12.firebasestorage.app',
    measurementId: 'G-KM8V1THY11',
  );
}
